### ISSUE TITLE
www.opengis.net not working ?

### ISSUE THREAD

**Issue by chkkbim** [tudelft3d/website-citygml#6]
Hi, I'm reading the CityGML v2 specification (OGC 12-019), to learn how to create model files.

Throughout the document, there are references to http://www.opengis.net/citygml/xxx, e.g. http://www.opengis.net/citygml/building/2.0. When I use my browser to go to these addresses, I get "Not found". Is there a new web address to use ?

Thank you.

**Comment by kkimmy** [comment]
http://www.opengis.net/citygml/building/2.0 is a URI associated with the namespace building in CityGML. A namespace just is a way of saying your definition of a "Building" is different from my definition of a "Building", even though their spelling is same. And this is specified with the URI. In my view, its not necessary that URI should always be an active one. 
If you are expecting to find the schema for CityGML building then you should check the attribute  "schemaLocation", its value is also a URL which is accessible and stores CityGML schemas for e.g.  http://schemas.opengis.net/citygml/building/2.0/building.xsd
