### ISSUE TITLE
"Land Use" Link (under Example Files for specific CityGML classes) is opening page with meaningless content

### ISSUE THREAD

**Issue by gogglya** [tudelft3d/website-citygml#9]
https://www.citygml.org/samplefiles/landuse/ is opening a page with meaningless content, It also does not have any links for CityGML files to download.

**Comment by gogglya** [comment]
![image](https://user-images.githubusercontent.com/39795698/40776149-8c6b7e6c-64e7-11e8-92f1-45a8b29423de.png)

**Comment by hugoledoux** [comment]
Thanks for pointing out, I removed the page.

([Bacon ipsum](https://baconipsum.com/) is not meaningless!)
